/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate employee and receive JWT token
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Invalidate current session token
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current employee
         * @description Get authenticated employee details
         */
        get: operations["getCurrentEmployee"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List employees
         * @description Get paginated list of employees in current organization
         */
        get: operations["listEmployees"];
        put?: never;
        /**
         * Create employee
         * @description Create new employee (admin/manager only)
         */
        post: operations["createEmployee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{employee_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get employee
         * @description Get employee by ID
         */
        get: operations["getEmployee"];
        put?: never;
        post?: never;
        /**
         * Delete employee
         * @description Soft delete employee (admin only)
         */
        delete: operations["deleteEmployee"];
        options?: never;
        head?: never;
        /**
         * Update employee
         * @description Update employee (admin/manager only)
         */
        patch: operations["updateEmployee"];
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List teams
         * @description Get all teams in current organization
         */
        get: operations["listTeams"];
        put?: never;
        /**
         * Create team
         * @description Create a new team in current organization (admin only)
         */
        post: operations["createTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{team_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get team
         * @description Get team by ID
         */
        get: operations["getTeam"];
        put?: never;
        post?: never;
        /**
         * Delete team
         * @description Delete a team (admin only)
         */
        delete: operations["deleteTeam"];
        options?: never;
        head?: never;
        /**
         * Update team
         * @description Update team details (admin only)
         */
        patch: operations["updateTeam"];
        trace?: never;
    };
    "/organizations/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current organization
         * @description Get details of authenticated employee's organization
         */
        get: operations["getCurrentOrganization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/current/claude-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set organization Claude token
         * @description Set the company-wide Claude API token (from 'claude setup-token').
         *     This token is used as default for all employees who don't have personal tokens.
         */
        put: operations["setOrganizationClaudeToken"];
        post?: never;
        /**
         * Delete organization Claude token
         * @description Remove the company-wide Claude API token
         */
        delete: operations["deleteOrganizationClaudeToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/me/claude-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set personal Claude token
         * @description Set employee's personal Claude API token (from 'claude setup-token').
         *     Personal tokens take precedence over organization tokens.
         */
        put: operations["setEmployeeClaudeToken"];
        post?: never;
        /**
         * Delete personal Claude token
         * @description Remove employee's personal Claude API token (will fall back to org token)
         */
        delete: operations["deleteEmployeeClaudeToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/me/claude-token/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Claude token status
         * @description Check which Claude token is active (personal, company, or none)
         */
        get: operations["getClaudeTokenStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/me/claude-token/effective": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get effective Claude token
         * @description Get the effective Claude API token for the current employee.
         *     Returns the personal token if set, otherwise the organization token.
         *     ⚠️ Security: Token is returned as plaintext, use HTTPS in production.
         */
        get: operations["getEffectiveClaudeToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List roles
         * @description Get available roles in organization
         */
        get: operations["listRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available agents
         * @description Get catalog of available AI agents (Claude Code, Cursor, Windsurf, etc.)
         */
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/current/agent-configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List org agent configurations
         * @description Get all agent configurations for the current organization
         */
        get: operations["listOrgAgentConfigs"];
        put?: never;
        /**
         * Create org agent configuration
         * @description Configure an agent at organization level (applies to all employees)
         */
        post: operations["createOrgAgentConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/current/agent-configs/{config_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org agent config UUID */
                config_id: string;
            };
            cookie?: never;
        };
        /**
         * Get org agent configuration
         * @description Get details of a specific org agent configuration
         */
        get: operations["getOrgAgentConfig"];
        put?: never;
        post?: never;
        /**
         * Delete org agent configuration
         * @description Remove an agent configuration from the organization
         */
        delete: operations["deleteOrgAgentConfig"];
        options?: never;
        head?: never;
        /**
         * Update org agent configuration
         * @description Update an existing org agent configuration
         */
        patch: operations["updateOrgAgentConfig"];
        trace?: never;
    };
    "/teams/{team_id}/agent-configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List team agent configs
         * @description Get all agent configurations for a specific team (overrides of org configs)
         */
        get: operations["listTeamAgentConfigs"];
        put?: never;
        /**
         * Create team agent config override
         * @description Create a team-level override for an agent configuration (admin/manager only)
         */
        post: operations["createTeamAgentConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{team_id}/agent-configs/{config_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get team agent config
         * @description Get details of a specific team agent configuration
         */
        get: operations["getTeamAgentConfig"];
        put?: never;
        post?: never;
        /**
         * Delete team agent config
         * @description Remove team-level override (reverts to org config) (admin/manager only)
         */
        delete: operations["deleteTeamAgentConfig"];
        options?: never;
        head?: never;
        /**
         * Update team agent config
         * @description Update team-level agent configuration override (admin/manager only)
         */
        patch: operations["updateTeamAgentConfig"];
        trace?: never;
    };
    "/employees/{employee_id}/agent-configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List employee agent configs
         * @description Get all agent configuration overrides for a specific employee
         */
        get: operations["listEmployeeAgentConfigs"];
        put?: never;
        /**
         * Create employee agent config override
         * @description Create an employee-level override for an agent configuration (admin/manager only)
         */
        post: operations["createEmployeeAgentConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{employee_id}/agent-configs/{config_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get employee agent config
         * @description Get details of a specific employee agent configuration override
         */
        get: operations["getEmployeeAgentConfig"];
        put?: never;
        post?: never;
        /**
         * Delete employee agent config
         * @description Remove employee-level override (reverts to team/org config) (admin/manager only)
         */
        delete: operations["deleteEmployeeAgentConfig"];
        options?: never;
        head?: never;
        /**
         * Update employee agent config
         * @description Update employee-level agent configuration override (admin/manager only)
         */
        patch: operations["updateEmployeeAgentConfig"];
        trace?: never;
    };
    "/employees/{employee_id}/agent-configs/resolved": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Employee UUID */
                employee_id: string;
            };
            cookie?: never;
        };
        /**
         * Get resolved agent configs for employee
         * @description Get all agent configurations for an employee with full hierarchy resolution
         *     (org → team → employee). This is the primary endpoint used by the CLI for sync.
         */
        get: operations["getEmployeeResolvedAgentConfigs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example validation_error */
            error: string;
            /** @example Email is required */
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        LoginRequest: {
            /**
             * Format: email
             * @example alice@acme.com
             */
            email: string;
            /**
             * Format: password
             * @example SecurePass123!
             */
            password: string;
        };
        LoginResponse: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            token: string;
            /** Format: date-time */
            expires_at: string;
            employee: components["schemas"]["Employee"];
        };
        Employee: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            org_id: string;
            /** Format: uuid */
            team_id?: string | null;
            /** @description Name of the team (populated in list endpoints) */
            readonly team_name?: string | null;
            /** Format: uuid */
            role_id: string;
            /** Format: email */
            email: string;
            full_name: string;
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "suspended" | "inactive";
            preferences?: {
                [key: string]: unknown;
            };
            /** @description Whether employee has configured a personal Claude API token */
            readonly has_personal_claude_token?: boolean;
            /** Format: date-time */
            readonly last_login_at?: string | null;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        CreateEmployeeRequest: {
            /** Format: email */
            email: string;
            full_name: string;
            /** Format: uuid */
            team_id?: string | null;
            /** Format: uuid */
            role_id: string;
            /** @default {} */
            preferences: {
                [key: string]: unknown;
            };
        };
        CreateEmployeeResponse: {
            employee: components["schemas"]["Employee"];
            /**
             * @description Temporary password for the new employee (only returned on creation)
             * @example aB3$xY9#mK2@pL7!
             */
            temporary_password: string;
        };
        UpdateEmployeeRequest: {
            full_name?: string;
            /** Format: uuid */
            team_id?: string | null;
            /** Format: uuid */
            role_id?: string;
            /** @enum {string} */
            status?: "active" | "suspended" | "inactive";
            preferences?: {
                [key: string]: unknown;
            };
        };
        ListEmployeesResponse: {
            employees: components["schemas"]["Employee"][];
            /**
             * Format: int64
             * @description Total number of employees matching the filter
             */
            total: number;
            /** @description Maximum number of results per page */
            limit: number;
            /** @description Number of results to skip */
            offset: number;
        };
        Organization: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            slug: string;
            /**
             * @default starter
             * @enum {string}
             */
            plan: "starter" | "professional" | "enterprise";
            settings?: {
                [key: string]: unknown;
            };
            /** @default 10 */
            max_employees: number;
            /** @default 3 */
            max_agents_per_employee: number;
            /** @description Whether organization has a Claude API token configured */
            readonly has_claude_token?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        Team: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            org_id: string;
            name: string;
            description?: string | null;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            /** @description Number of employees in this team */
            readonly member_count?: number;
            /** @description Number of agent configurations for this team */
            readonly agent_config_count?: number;
        };
        Role: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            description?: string | null;
            permissions?: string[];
            /** Format: date-time */
            readonly created_at?: string;
            /** @description Number of employees with this role */
            readonly employee_count?: number;
        };
        SetClaudeTokenRequest: {
            /**
             * @description Claude API token from 'claude setup-token' command
             * @example eyJhbGci...
             */
            token: string;
        };
        ClaudeTokenStatusResponse: {
            /** Format: uuid */
            readonly employee_id?: string;
            /** @description Whether employee has configured a personal token */
            has_personal_token: boolean;
            /** @description Whether organization has a company-wide token */
            has_company_token: boolean;
            /**
             * @description Which token will be used (personal takes precedence)
             * @enum {string}
             */
            active_token_source: "personal" | "company" | "none";
        };
        ClaudeTokenResponse: {
            success: boolean;
            /** @example Claude API token updated successfully */
            message: string;
        };
        EffectiveClaudeTokenResponse: {
            /**
             * @description The effective Claude API token (plaintext)
             * @example sk-ant-api03-abc...
             */
            token: string;
            /**
             * @description Source of the token (personal or company)
             * @enum {string}
             */
            source: "personal" | "company";
            /**
             * Format: uuid
             * @description Organization ID
             */
            org_id: string;
            /** @description Organization name */
            org_name: string;
            /**
             * Format: uuid
             * @description Employee ID
             */
            employee_id?: string;
        };
        Agent: {
            /** Format: uuid */
            readonly id: string;
            /** @example Claude Code */
            name: string;
            /** @example claude-code */
            type: string;
            /** @example AI-powered code assistant with deep codebase understanding */
            description: string;
            /** @example anthropic */
            provider: string;
            /**
             * @example {
             *       "model": "claude-3-5-sonnet-20241022",
             *       "max_tokens": 8192
             *     }
             */
            default_config?: {
                [key: string]: unknown;
            };
            /**
             * @example [
             *       "code_generation",
             *       "code_review",
             *       "refactoring"
             *     ]
             */
            capabilities?: string[];
            /** @example anthropic */
            llm_provider: string;
            /** @example claude-3-5-sonnet-20241022 */
            llm_model: string;
            /** @default true */
            is_public: boolean;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        ListAgentsResponse: {
            agents: components["schemas"]["Agent"][];
            /** @example 5 */
            total: number;
        };
        OrgAgentConfig: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            org_id: string;
            /** Format: uuid */
            agent_id: string;
            /** @example Claude Code */
            readonly agent_name?: string;
            /** @example claude-code */
            readonly agent_type?: string;
            /** @example anthropic */
            readonly agent_provider?: string;
            /**
             * @description Full agent configuration (not an override)
             * @example {
             *       "model": "claude-3-5-sonnet-20241022",
             *       "temperature": 0.2,
             *       "max_tokens": 8192
             *     }
             */
            config: {
                [key: string]: unknown;
            };
            /** @default true */
            is_enabled: boolean;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        CreateOrgAgentConfigRequest: {
            /** Format: uuid */
            agent_id: string;
            /**
             * @example {
             *       "model": "claude-3-5-sonnet-20241022",
             *       "temperature": 0.2
             *     }
             */
            config: {
                [key: string]: unknown;
            };
            /** @default true */
            is_enabled: boolean;
        };
        UpdateOrgAgentConfigRequest: {
            /**
             * @example {
             *       "temperature": 0.5
             *     }
             */
            config?: {
                [key: string]: unknown;
            };
            is_enabled?: boolean;
        };
        ListOrgAgentConfigsResponse: {
            configs: components["schemas"]["OrgAgentConfig"][];
            /** @example 3 */
            total: number;
        };
        ResolvedAgentConfig: {
            /** Format: uuid */
            agent_id: string;
            /** @example Claude Code */
            agent_name: string;
            /** @example claude-code */
            agent_type: string;
            /** @example anthropic */
            provider: string;
            /**
             * @description Fully resolved config (org → team → employee merged)
             * @example {
             *       "model": "claude-3-5-sonnet-20241022",
             *       "temperature": 0.5,
             *       "max_tokens": 16384
             *     }
             */
            config: {
                [key: string]: unknown;
            };
            /**
             * @description Concatenated system prompts from all hierarchy levels
             * @example You are a helpful coding assistant.
             */
            system_prompt: string;
            /** @description True only if enabled at all levels */
            is_enabled: boolean;
            /** @description Token for CLI sync tracking */
            sync_token?: string | null;
            /**
             * Format: date-time
             * @description Last time config was synced to CLI
             */
            last_synced_at?: string | null;
        };
        ListResolvedAgentConfigsResponse: {
            configs: components["schemas"]["ResolvedAgentConfig"][];
            /** @example 3 */
            total: number;
        };
        CreateTeamRequest: {
            /** @example Engineering */
            name: string;
            /** @example Software development team */
            description?: string | null;
        };
        UpdateTeamRequest: {
            name?: string;
            description?: string | null;
        };
        ListTeamsResponse: {
            teams: components["schemas"]["Team"][];
            /** @example 5 */
            total: number;
        };
        TeamAgentConfig: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            team_id: string;
            /** Format: uuid */
            agent_id: string;
            /** @example Claude Code */
            readonly agent_name?: string;
            /** @example ide */
            readonly agent_type?: string;
            /** @example anthropic */
            readonly agent_provider?: string;
            /**
             * @description Overrides org-level config (deep merge)
             * @example {
             *       "api_endpoint": "https://custom.example.com",
             *       "features": {
             *         "autocomplete": false
             *       }
             *     }
             */
            config_override: {
                [key: string]: unknown;
            };
            /** @description Can disable for team even if org has it enabled */
            is_enabled: boolean;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        CreateTeamAgentConfigRequest: {
            /** Format: uuid */
            agent_id: string;
            /** @description Only include fields you want to override from org config */
            config_override: {
                [key: string]: unknown;
            };
            /** @default true */
            is_enabled: boolean;
        };
        UpdateTeamAgentConfigRequest: {
            config_override?: {
                [key: string]: unknown;
            };
            is_enabled?: boolean;
        };
        ListTeamAgentConfigsResponse: {
            configs: components["schemas"]["TeamAgentConfig"][];
            total: number;
        };
        EmployeeAgentConfig: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            employee_id: string;
            /** Format: uuid */
            agent_id: string;
            readonly agent_name?: string;
            readonly agent_type?: string;
            readonly agent_provider?: string;
            /** @description Overrides team/org config (deep merge) */
            config_override: {
                [key: string]: unknown;
            };
            /** @description Can disable for employee even if team/org has it enabled */
            is_enabled: boolean;
            /** @description Token used by CLI for sync validation */
            sync_token?: string | null;
            /**
             * Format: date-time
             * @description Last time CLI synced this config
             */
            last_synced_at?: string | null;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        CreateEmployeeAgentConfigRequest: {
            /** Format: uuid */
            agent_id: string;
            /** @description Only include fields you want to override */
            config_override: {
                [key: string]: unknown;
            };
            /** @default true */
            is_enabled: boolean;
        };
        UpdateEmployeeAgentConfigRequest: {
            config_override?: {
                [key: string]: unknown;
            };
            is_enabled?: boolean;
        };
        ListEmployeeAgentConfigsResponse: {
            configs: components["schemas"]["EmployeeAgentConfig"][];
            total: number;
        };
        PaginationMeta: {
            /** @example 100 */
            total: number;
            /** @example 1 */
            page: number;
            /** @example 20 */
            per_page: number;
            /** @example 5 */
            total_pages: number;
        };
        EmployeeList: {
            data: components["schemas"]["Employee"][];
            meta: components["schemas"]["PaginationMeta"];
        };
    };
    responses: never;
    parameters: {
        /** @description Employee UUID */
        EmployeeId: string;
        /** @description Team UUID */
        TeamId: string;
        /** @description Agent configuration UUID */
        ConfigId: string;
        /** @description Page number */
        Page: number;
        /** @description Items per page */
        PerPage: number;
        /** @description Filter by status */
        Status: "active" | "suspended" | "inactive";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout successful */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCurrentEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current employee */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listEmployees: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: components["parameters"]["Page"];
                /** @description Items per page */
                per_page?: components["parameters"]["PerPage"];
                /** @description Filter by status */
                status?: components["parameters"]["Status"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Employee list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEmployeesResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEmployeeRequest"];
            };
        };
        responses: {
            /** @description Employee created with temporary password */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateEmployeeResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden - insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Employee UUID */
                employee_id: components["parameters"]["EmployeeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Employee details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Employee not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Employee UUID */
                employee_id: components["parameters"]["EmployeeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Employee deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Employee not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Employee UUID */
                employee_id: components["parameters"]["EmployeeId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEmployeeRequest"];
            };
        };
        responses: {
            /** @description Employee updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Employee not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listTeams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Team list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListTeamsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTeamRequest"];
            };
        };
        responses: {
            /** @description Team created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team UUID */
                team_id: components["parameters"]["TeamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Team details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Team not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team UUID */
                team_id: components["parameters"]["TeamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Team deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Team not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team UUID */
                team_id: components["parameters"]["TeamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTeamRequest"];
            };
        };
        responses: {
            /** @description Team updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Team not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCurrentOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    setOrganizationClaudeToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetClaudeTokenRequest"];
            };
        };
        responses: {
            /** @description Token set successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaudeTokenResponse"];
                };
            };
            /** @description Invalid token format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteOrganizationClaudeToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaudeTokenResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    setEmployeeClaudeToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetClaudeTokenRequest"];
            };
        };
        responses: {
            /** @description Token set successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaudeTokenResponse"];
                };
            };
            /** @description Invalid token format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteEmployeeClaudeToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaudeTokenResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getClaudeTokenStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaudeTokenStatusResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getEffectiveClaudeToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Effective token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EffectiveClaudeTokenResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No token configured */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Role list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Role"][];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAgentsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listOrgAgentConfigs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Org agent configs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListOrgAgentConfigsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createOrgAgentConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrgAgentConfigRequest"];
            };
        };
        responses: {
            /** @description Config created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgAgentConfig"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Agent already configured for this org */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getOrgAgentConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org agent config UUID */
                config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Org agent config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgAgentConfig"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Config not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteOrgAgentConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org agent config UUID */
                config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Config deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Config not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateOrgAgentConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org agent config UUID */
                config_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrgAgentConfigRequest"];
            };
        };
        responses: {
            /** @description Config updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgAgentConfig"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Config not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listTeamAgentConfigs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team UUID */
                team_id: components["parameters"]["TeamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Team agent configs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListTeamAgentConfigsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Team not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createTeamAgentConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team UUID */
                team_id: components["parameters"]["TeamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTeamAgentConfigRequest"];
            };
        };
        responses: {
            /** @description Team agent config created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamAgentConfig"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Team or agent not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Config already exists for this agent */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getTeamAgentConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team UUID */
                team_id: components["parameters"]["TeamId"];
                /** @description Agent configuration UUID */
                config_id: components["parameters"]["ConfigId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Team agent config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamAgentConfig"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Config not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteTeamAgentConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team UUID */
                team_id: components["parameters"]["TeamId"];
                /** @description Agent configuration UUID */
                config_id: components["parameters"]["ConfigId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Config deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Config not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateTeamAgentConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team UUID */
                team_id: components["parameters"]["TeamId"];
                /** @description Agent configuration UUID */
                config_id: components["parameters"]["ConfigId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTeamAgentConfigRequest"];
            };
        };
        responses: {
            /** @description Config updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamAgentConfig"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Config not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listEmployeeAgentConfigs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Employee UUID */
                employee_id: components["parameters"]["EmployeeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Employee agent configs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEmployeeAgentConfigsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Employee not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createEmployeeAgentConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Employee UUID */
                employee_id: components["parameters"]["EmployeeId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEmployeeAgentConfigRequest"];
            };
        };
        responses: {
            /** @description Employee agent config created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeAgentConfig"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Employee or agent not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Config already exists for this agent */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getEmployeeAgentConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Employee UUID */
                employee_id: components["parameters"]["EmployeeId"];
                /** @description Agent configuration UUID */
                config_id: components["parameters"]["ConfigId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Employee agent config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeAgentConfig"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Config not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteEmployeeAgentConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Employee UUID */
                employee_id: components["parameters"]["EmployeeId"];
                /** @description Agent configuration UUID */
                config_id: components["parameters"]["ConfigId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Config deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Config not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateEmployeeAgentConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Employee UUID */
                employee_id: components["parameters"]["EmployeeId"];
                /** @description Agent configuration UUID */
                config_id: components["parameters"]["ConfigId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEmployeeAgentConfigRequest"];
            };
        };
        responses: {
            /** @description Config updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeAgentConfig"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Config not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getEmployeeResolvedAgentConfigs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Employee UUID */
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resolved agent configs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResolvedAgentConfigsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Employee not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
