openapi: 3.0.3
info:
  title: Ubik Enterprise - AI Agent Management Platform
  description: |
    Centralized platform for managing employee AI agent and MCP configurations.
    
    Companies can:
    - Manage employees, teams, and roles
    - Configure AI agents (Claude Code, Cursor, Windsurf)
    - Configure MCP servers
    - Set policies and approval workflows
    - Track usage and costs
  version: 1.0.0
  contact:
    name: API Support
    email: support@ubik-enterprise.com

servers:
  - url: http://localhost:3001/api/v1
    description: Local development
  - url: https://api.ubik-enterprise.com/api/v1
    description: Production

tags:
  - name: auth
    description: Authentication and session management
  - name: employees
    description: Employee management
  - name: organizations
    description: Organization and team management
  - name: agents
    description: Agent catalog and configuration
  - name: mcps
    description: MCP catalog and configuration
  - name: approvals
    description: Approval workflows

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # Error responses
    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          example: "validation_error"
        message:
          type: string
          example: "Email is required"
        details:
          type: object
          additionalProperties: true

    # Auth schemas
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: "alice@acme.com"
        password:
          type: string
          format: password
          minLength: 8
          example: "SecurePass123!"

    LoginResponse:
      type: object
      required:
        - token
        - expires_at
        - employee
      properties:
        token:
          type: string
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        expires_at:
          type: string
          format: date-time
        employee:
          $ref: '#/components/schemas/Employee'

    # Core domain schemas
    Employee:
      type: object
      required:
        - id
        - org_id
        - email
        - full_name
        - role_id
        - status
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        org_id:
          type: string
          format: uuid
        team_id:
          type: string
          format: uuid
          nullable: true
        role_id:
          type: string
          format: uuid
        email:
          type: string
          format: email
          maxLength: 255
        full_name:
          type: string
          minLength: 1
          maxLength: 255
        status:
          type: string
          enum: [active, suspended, inactive]
          default: active
        preferences:
          type: object
          additionalProperties: true
        last_login_at:
          type: string
          format: date-time
          nullable: true
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true

    CreateEmployeeRequest:
      type: object
      required:
        - email
        - full_name
        - role_id
      properties:
        email:
          type: string
          format: email
          maxLength: 255
        full_name:
          type: string
          minLength: 1
          maxLength: 255
        team_id:
          type: string
          format: uuid
          nullable: true
        role_id:
          type: string
          format: uuid
        preferences:
          type: object
          additionalProperties: true
          default: {}

    UpdateEmployeeRequest:
      type: object
      properties:
        full_name:
          type: string
          minLength: 1
          maxLength: 255
        team_id:
          type: string
          format: uuid
          nullable: true
        role_id:
          type: string
          format: uuid
        status:
          type: string
          enum: [active, suspended, inactive]
        preferences:
          type: object
          additionalProperties: true

    ListEmployeesResponse:
      type: object
      required:
        - employees
        - total
        - limit
        - offset
      properties:
        employees:
          type: array
          items:
            $ref: '#/components/schemas/Employee'
        total:
          type: integer
          format: int64
          description: Total number of employees matching the filter
        limit:
          type: integer
          description: Maximum number of results per page
        offset:
          type: integer
          description: Number of results to skip

    Organization:
      type: object
      required:
        - id
        - name
        - slug
        - plan
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 255
        slug:
          type: string
          maxLength: 100
          pattern: '^[a-z0-9-]+$'
        plan:
          type: string
          enum: [starter, professional, enterprise]
          default: starter
        settings:
          type: object
          additionalProperties: true
        max_employees:
          type: integer
          minimum: 1
          default: 10
        max_agents_per_employee:
          type: integer
          minimum: 1
          default: 3
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true

    Team:
      type: object
      required:
        - id
        - org_id
        - name
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        org_id:
          type: string
          format: uuid
        name:
          type: string
          maxLength: 255
        description:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true

    Role:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 100
        description:
          type: string
          nullable: true
        permissions:
          type: array
          items:
            type: string
        created_at:
          type: string
          format: date-time
          readOnly: true

    # Agent schemas
    Agent:
      type: object
      required:
        - id
        - name
        - type
        - description
        - provider
        - llm_provider
        - llm_model
        - is_public
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 255
          example: "Claude Code"
        type:
          type: string
          maxLength: 100
          example: "claude-code"
        description:
          type: string
          example: "AI-powered code assistant with deep codebase understanding"
        provider:
          type: string
          maxLength: 100
          example: "anthropic"
        default_config:
          type: object
          additionalProperties: true
          example: {"model": "claude-3-5-sonnet-20241022", "max_tokens": 8192}
        capabilities:
          type: array
          items:
            type: string
          example: ["code_generation", "code_review", "refactoring"]
        llm_provider:
          type: string
          maxLength: 50
          example: "anthropic"
        llm_model:
          type: string
          maxLength: 100
          example: "claude-3-5-sonnet-20241022"
        is_public:
          type: boolean
          default: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true

    ListAgentsResponse:
      type: object
      required:
        - agents
        - total
      properties:
        agents:
          type: array
          items:
            $ref: '#/components/schemas/Agent'
        total:
          type: integer
          example: 5

    # Pagination
    PaginationMeta:
      type: object
      required:
        - total
        - page
        - per_page
        - total_pages
      properties:
        total:
          type: integer
          example: 100
        page:
          type: integer
          example: 1
        per_page:
          type: integer
          example: 20
        total_pages:
          type: integer
          example: 5

    EmployeeList:
      type: object
      required:
        - data
        - meta
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Employee'
        meta:
          $ref: '#/components/schemas/PaginationMeta'

  parameters:
    EmployeeId:
      name: employee_id
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: Employee UUID

    Page:
      name: page
      in: query
      schema:
        type: integer
        minimum: 1
        default: 1
      description: Page number

    PerPage:
      name: per_page
      in: query
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
      description: Items per page

    Status:
      name: status
      in: query
      schema:
        type: string
        enum: [active, suspended, inactive]
      description: Filter by status

paths:
  # ============================================================================
  # Authentication
  # ============================================================================
  /auth/login:
    post:
      tags:
        - auth
      summary: Login
      description: Authenticate employee and receive JWT token
      operationId: login
      security: []  # No auth required for login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/logout:
    post:
      tags:
        - auth
      summary: Logout
      description: Invalidate current session token
      operationId: logout
      responses:
        '204':
          description: Logout successful
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/me:
    get:
      tags:
        - auth
      summary: Get current employee
      description: Get authenticated employee details
      operationId: getCurrentEmployee
      responses:
        '200':
          description: Current employee
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  # ============================================================================
  # Employees
  # ============================================================================
  /employees:
    get:
      tags:
        - employees
      summary: List employees
      description: Get paginated list of employees in current organization
      operationId: listEmployees
      parameters:
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PerPage'
        - $ref: '#/components/parameters/Status'
      responses:
        '200':
          description: Employee list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListEmployeesResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      tags:
        - employees
      summary: Create employee
      description: Create new employee (admin/manager only)
      operationId: createEmployee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEmployeeRequest'
      responses:
        '201':
          description: Employee created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /employees/{employee_id}:
    get:
      tags:
        - employees
      summary: Get employee
      description: Get employee by ID
      operationId: getEmployee
      parameters:
        - $ref: '#/components/parameters/EmployeeId'
      responses:
        '200':
          description: Employee details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Employee not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    patch:
      tags:
        - employees
      summary: Update employee
      description: Update employee (admin/manager only)
      operationId: updateEmployee
      parameters:
        - $ref: '#/components/parameters/EmployeeId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEmployeeRequest'
      responses:
        '200':
          description: Employee updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Employee not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      tags:
        - employees
      summary: Delete employee
      description: Soft delete employee (admin only)
      operationId: deleteEmployee
      parameters:
        - $ref: '#/components/parameters/EmployeeId'
      responses:
        '204':
          description: Employee deleted
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Employee not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  # ============================================================================
  # Organizations
  # ============================================================================
  /organizations/current:
    get:
      tags:
        - organizations
      summary: Get current organization
      description: Get details of authenticated employee's organization
      operationId: getCurrentOrganization
      responses:
        '200':
          description: Organization details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /roles:
    get:
      tags:
        - organizations
      summary: List roles
      description: Get available roles in organization
      operationId: listRoles
      responses:
        '200':
          description: Role list
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Role'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  # ============================================================================
  # Agents
  # ============================================================================
  /agents:
    get:
      tags:
        - agents
      summary: List available agents
      description: Get catalog of available AI agents (Claude Code, Cursor, Windsurf, etc.)
      operationId: listAgents
      responses:
        '200':
          description: Agent catalog
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListAgentsResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
