// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces.go
//
// Generated by this command:
//
//	mockgen -source=../interfaces.go -destination=interfaces_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	http "net/http"
	reflect "reflect"

	cli "github.com/sergeirastrigin/ubik-enterprise/services/cli/internal"
	gomock "go.uber.org/mock/gomock"
)

// MockConfigManagerInterface is a mock of ConfigManagerInterface interface.
type MockConfigManagerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockConfigManagerInterfaceMockRecorder
}

// MockConfigManagerInterfaceMockRecorder is the mock recorder for MockConfigManagerInterface.
type MockConfigManagerInterfaceMockRecorder struct {
	mock *MockConfigManagerInterface
}

// NewMockConfigManagerInterface creates a new mock instance.
func NewMockConfigManagerInterface(ctrl *gomock.Controller) *MockConfigManagerInterface {
	mock := &MockConfigManagerInterface{ctrl: ctrl}
	mock.recorder = &MockConfigManagerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigManagerInterface) EXPECT() *MockConfigManagerInterfaceMockRecorder {
	return m.recorder
}

// Clear mocks base method.
func (m *MockConfigManagerInterface) Clear() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear")
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear.
func (mr *MockConfigManagerInterfaceMockRecorder) Clear() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockConfigManagerInterface)(nil).Clear))
}

// GetConfigPath mocks base method.
func (m *MockConfigManagerInterface) GetConfigPath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigPath")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetConfigPath indicates an expected call of GetConfigPath.
func (mr *MockConfigManagerInterfaceMockRecorder) GetConfigPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigPath", reflect.TypeOf((*MockConfigManagerInterface)(nil).GetConfigPath))
}

// IsAuthenticated mocks base method.
func (m *MockConfigManagerInterface) IsAuthenticated() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAuthenticated")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAuthenticated indicates an expected call of IsAuthenticated.
func (mr *MockConfigManagerInterfaceMockRecorder) IsAuthenticated() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAuthenticated", reflect.TypeOf((*MockConfigManagerInterface)(nil).IsAuthenticated))
}

// IsTokenValid mocks base method.
func (m *MockConfigManagerInterface) IsTokenValid() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTokenValid")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTokenValid indicates an expected call of IsTokenValid.
func (mr *MockConfigManagerInterfaceMockRecorder) IsTokenValid() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTokenValid", reflect.TypeOf((*MockConfigManagerInterface)(nil).IsTokenValid))
}

// Load mocks base method.
func (m *MockConfigManagerInterface) Load() (*cli.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load")
	ret0, _ := ret[0].(*cli.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockConfigManagerInterfaceMockRecorder) Load() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockConfigManagerInterface)(nil).Load))
}

// Save mocks base method.
func (m *MockConfigManagerInterface) Save(config *cli.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", config)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockConfigManagerInterfaceMockRecorder) Save(config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockConfigManagerInterface)(nil).Save), config)
}

// MockAPIClientInterface is a mock of APIClientInterface interface.
type MockAPIClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAPIClientInterfaceMockRecorder
}

// MockAPIClientInterfaceMockRecorder is the mock recorder for MockAPIClientInterface.
type MockAPIClientInterfaceMockRecorder struct {
	mock *MockAPIClientInterface
}

// NewMockAPIClientInterface creates a new mock instance.
func NewMockAPIClientInterface(ctrl *gomock.Controller) *MockAPIClientInterface {
	mock := &MockAPIClientInterface{ctrl: ctrl}
	mock.recorder = &MockAPIClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIClientInterface) EXPECT() *MockAPIClientInterfaceMockRecorder {
	return m.recorder
}

// CreateLog mocks base method.
func (m *MockAPIClientInterface) CreateLog(ctx context.Context, entry cli.LogEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLog", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLog indicates an expected call of CreateLog.
func (mr *MockAPIClientInterfaceMockRecorder) CreateLog(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLog", reflect.TypeOf((*MockAPIClientInterface)(nil).CreateLog), ctx, entry)
}

// CreateLogBatch mocks base method.
func (m *MockAPIClientInterface) CreateLogBatch(ctx context.Context, entries []cli.LogEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLogBatch", ctx, entries)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLogBatch indicates an expected call of CreateLogBatch.
func (mr *MockAPIClientInterfaceMockRecorder) CreateLogBatch(ctx, entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLogBatch", reflect.TypeOf((*MockAPIClientInterface)(nil).CreateLogBatch), ctx, entries)
}

// GetClaudeCodeConfig mocks base method.
func (m *MockAPIClientInterface) GetClaudeCodeConfig(ctx context.Context) (*cli.ClaudeCodeSyncResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClaudeCodeConfig", ctx)
	ret0, _ := ret[0].(*cli.ClaudeCodeSyncResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClaudeCodeConfig indicates an expected call of GetClaudeCodeConfig.
func (mr *MockAPIClientInterfaceMockRecorder) GetClaudeCodeConfig(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClaudeCodeConfig", reflect.TypeOf((*MockAPIClientInterface)(nil).GetClaudeCodeConfig), ctx)
}

// GetClaudeTokenStatus mocks base method.
func (m *MockAPIClientInterface) GetClaudeTokenStatus(ctx context.Context) (*cli.ClaudeTokenStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClaudeTokenStatus", ctx)
	ret0, _ := ret[0].(*cli.ClaudeTokenStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClaudeTokenStatus indicates an expected call of GetClaudeTokenStatus.
func (mr *MockAPIClientInterfaceMockRecorder) GetClaudeTokenStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClaudeTokenStatus", reflect.TypeOf((*MockAPIClientInterface)(nil).GetClaudeTokenStatus), ctx)
}

// GetCurrentEmployee mocks base method.
func (m *MockAPIClientInterface) GetCurrentEmployee(ctx context.Context) (*cli.EmployeeInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentEmployee", ctx)
	ret0, _ := ret[0].(*cli.EmployeeInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentEmployee indicates an expected call of GetCurrentEmployee.
func (mr *MockAPIClientInterfaceMockRecorder) GetCurrentEmployee(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentEmployee", reflect.TypeOf((*MockAPIClientInterface)(nil).GetCurrentEmployee), ctx)
}

// GetEffectiveClaudeToken mocks base method.
func (m *MockAPIClientInterface) GetEffectiveClaudeToken(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEffectiveClaudeToken", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEffectiveClaudeToken indicates an expected call of GetEffectiveClaudeToken.
func (mr *MockAPIClientInterfaceMockRecorder) GetEffectiveClaudeToken(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEffectiveClaudeToken", reflect.TypeOf((*MockAPIClientInterface)(nil).GetEffectiveClaudeToken), ctx)
}

// GetEffectiveClaudeTokenInfo mocks base method.
func (m *MockAPIClientInterface) GetEffectiveClaudeTokenInfo(ctx context.Context) (*cli.EffectiveClaudeTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEffectiveClaudeTokenInfo", ctx)
	ret0, _ := ret[0].(*cli.EffectiveClaudeTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEffectiveClaudeTokenInfo indicates an expected call of GetEffectiveClaudeTokenInfo.
func (mr *MockAPIClientInterfaceMockRecorder) GetEffectiveClaudeTokenInfo(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEffectiveClaudeTokenInfo", reflect.TypeOf((*MockAPIClientInterface)(nil).GetEffectiveClaudeTokenInfo), ctx)
}

// GetEmployeeAgentConfigs mocks base method.
func (m *MockAPIClientInterface) GetEmployeeAgentConfigs(ctx context.Context, employeeID string) ([]cli.EmployeeAgentConfigResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeAgentConfigs", ctx, employeeID)
	ret0, _ := ret[0].([]cli.EmployeeAgentConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeAgentConfigs indicates an expected call of GetEmployeeAgentConfigs.
func (mr *MockAPIClientInterfaceMockRecorder) GetEmployeeAgentConfigs(ctx, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeAgentConfigs", reflect.TypeOf((*MockAPIClientInterface)(nil).GetEmployeeAgentConfigs), ctx, employeeID)
}

// GetEmployeeInfo mocks base method.
func (m *MockAPIClientInterface) GetEmployeeInfo(ctx context.Context, employeeID string) (*cli.EmployeeInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeInfo", ctx, employeeID)
	ret0, _ := ret[0].(*cli.EmployeeInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeInfo indicates an expected call of GetEmployeeInfo.
func (mr *MockAPIClientInterfaceMockRecorder) GetEmployeeInfo(ctx, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeInfo", reflect.TypeOf((*MockAPIClientInterface)(nil).GetEmployeeInfo), ctx, employeeID)
}

// GetEmployeeSkill mocks base method.
func (m *MockAPIClientInterface) GetEmployeeSkill(ctx context.Context, skillID string) (*cli.EmployeeSkill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeSkill", ctx, skillID)
	ret0, _ := ret[0].(*cli.EmployeeSkill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeSkill indicates an expected call of GetEmployeeSkill.
func (mr *MockAPIClientInterfaceMockRecorder) GetEmployeeSkill(ctx, skillID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeSkill", reflect.TypeOf((*MockAPIClientInterface)(nil).GetEmployeeSkill), ctx, skillID)
}

// GetLogs mocks base method.
func (m *MockAPIClientInterface) GetLogs(ctx context.Context, params cli.GetLogsParams) (*cli.APILogsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogs", ctx, params)
	ret0, _ := ret[0].(*cli.APILogsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLogs indicates an expected call of GetLogs.
func (mr *MockAPIClientInterfaceMockRecorder) GetLogs(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogs", reflect.TypeOf((*MockAPIClientInterface)(nil).GetLogs), ctx, params)
}

// GetMyResolvedAgentConfigs mocks base method.
func (m *MockAPIClientInterface) GetMyResolvedAgentConfigs(ctx context.Context) ([]cli.AgentConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyResolvedAgentConfigs", ctx)
	ret0, _ := ret[0].([]cli.AgentConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyResolvedAgentConfigs indicates an expected call of GetMyResolvedAgentConfigs.
func (mr *MockAPIClientInterfaceMockRecorder) GetMyResolvedAgentConfigs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyResolvedAgentConfigs", reflect.TypeOf((*MockAPIClientInterface)(nil).GetMyResolvedAgentConfigs), ctx)
}

// GetOrgAgentConfigs mocks base method.
func (m *MockAPIClientInterface) GetOrgAgentConfigs(ctx context.Context) ([]cli.OrgAgentConfigResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrgAgentConfigs", ctx)
	ret0, _ := ret[0].([]cli.OrgAgentConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrgAgentConfigs indicates an expected call of GetOrgAgentConfigs.
func (mr *MockAPIClientInterfaceMockRecorder) GetOrgAgentConfigs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrgAgentConfigs", reflect.TypeOf((*MockAPIClientInterface)(nil).GetOrgAgentConfigs), ctx)
}

// GetResolvedAgentConfigs mocks base method.
func (m *MockAPIClientInterface) GetResolvedAgentConfigs(ctx context.Context, employeeID string) ([]cli.AgentConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResolvedAgentConfigs", ctx, employeeID)
	ret0, _ := ret[0].([]cli.AgentConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResolvedAgentConfigs indicates an expected call of GetResolvedAgentConfigs.
func (mr *MockAPIClientInterfaceMockRecorder) GetResolvedAgentConfigs(ctx, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResolvedAgentConfigs", reflect.TypeOf((*MockAPIClientInterface)(nil).GetResolvedAgentConfigs), ctx, employeeID)
}

// GetSkill mocks base method.
func (m *MockAPIClientInterface) GetSkill(ctx context.Context, skillID string) (*cli.Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSkill", ctx, skillID)
	ret0, _ := ret[0].(*cli.Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSkill indicates an expected call of GetSkill.
func (mr *MockAPIClientInterfaceMockRecorder) GetSkill(ctx, skillID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSkill", reflect.TypeOf((*MockAPIClientInterface)(nil).GetSkill), ctx, skillID)
}

// GetTeamAgentConfigs mocks base method.
func (m *MockAPIClientInterface) GetTeamAgentConfigs(ctx context.Context, teamID string) ([]cli.TeamAgentConfigResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamAgentConfigs", ctx, teamID)
	ret0, _ := ret[0].([]cli.TeamAgentConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamAgentConfigs indicates an expected call of GetTeamAgentConfigs.
func (mr *MockAPIClientInterfaceMockRecorder) GetTeamAgentConfigs(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamAgentConfigs", reflect.TypeOf((*MockAPIClientInterface)(nil).GetTeamAgentConfigs), ctx, teamID)
}

// ListEmployeeSkills mocks base method.
func (m *MockAPIClientInterface) ListEmployeeSkills(ctx context.Context) (*cli.ListEmployeeSkillsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmployeeSkills", ctx)
	ret0, _ := ret[0].(*cli.ListEmployeeSkillsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEmployeeSkills indicates an expected call of ListEmployeeSkills.
func (mr *MockAPIClientInterfaceMockRecorder) ListEmployeeSkills(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmployeeSkills", reflect.TypeOf((*MockAPIClientInterface)(nil).ListEmployeeSkills), ctx)
}

// ListSkills mocks base method.
func (m *MockAPIClientInterface) ListSkills(ctx context.Context) (*cli.ListSkillsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSkills", ctx)
	ret0, _ := ret[0].(*cli.ListSkillsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSkills indicates an expected call of ListSkills.
func (mr *MockAPIClientInterfaceMockRecorder) ListSkills(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSkills", reflect.TypeOf((*MockAPIClientInterface)(nil).ListSkills), ctx)
}

// Login mocks base method.
func (m *MockAPIClientInterface) Login(ctx context.Context, email, password string) (*cli.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(*cli.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAPIClientInterfaceMockRecorder) Login(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAPIClientInterface)(nil).Login), ctx, email, password)
}

// SetBaseURL mocks base method.
func (m *MockAPIClientInterface) SetBaseURL(url string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBaseURL", url)
}

// SetBaseURL indicates an expected call of SetBaseURL.
func (mr *MockAPIClientInterfaceMockRecorder) SetBaseURL(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBaseURL", reflect.TypeOf((*MockAPIClientInterface)(nil).SetBaseURL), url)
}

// SetHTTPClient mocks base method.
func (m *MockAPIClientInterface) SetHTTPClient(client *http.Client) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetHTTPClient", client)
}

// SetHTTPClient indicates an expected call of SetHTTPClient.
func (mr *MockAPIClientInterfaceMockRecorder) SetHTTPClient(client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHTTPClient", reflect.TypeOf((*MockAPIClientInterface)(nil).SetHTTPClient), client)
}

// SetToken mocks base method.
func (m *MockAPIClientInterface) SetToken(token string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetToken", token)
}

// SetToken indicates an expected call of SetToken.
func (mr *MockAPIClientInterfaceMockRecorder) SetToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetToken", reflect.TypeOf((*MockAPIClientInterface)(nil).SetToken), token)
}

// MockAuthServiceInterface is a mock of AuthServiceInterface interface.
type MockAuthServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceInterfaceMockRecorder
}

// MockAuthServiceInterfaceMockRecorder is the mock recorder for MockAuthServiceInterface.
type MockAuthServiceInterfaceMockRecorder struct {
	mock *MockAuthServiceInterface
}

// NewMockAuthServiceInterface creates a new mock instance.
func NewMockAuthServiceInterface(ctrl *gomock.Controller) *MockAuthServiceInterface {
	mock := &MockAuthServiceInterface{ctrl: ctrl}
	mock.recorder = &MockAuthServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthServiceInterface) EXPECT() *MockAuthServiceInterfaceMockRecorder {
	return m.recorder
}

// GetConfig mocks base method.
func (m *MockAuthServiceInterface) GetConfig() (*cli.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig")
	ret0, _ := ret[0].(*cli.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockAuthServiceInterfaceMockRecorder) GetConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockAuthServiceInterface)(nil).GetConfig))
}

// IsAuthenticated mocks base method.
func (m *MockAuthServiceInterface) IsAuthenticated() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAuthenticated")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAuthenticated indicates an expected call of IsAuthenticated.
func (mr *MockAuthServiceInterfaceMockRecorder) IsAuthenticated() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAuthenticated", reflect.TypeOf((*MockAuthServiceInterface)(nil).IsAuthenticated))
}

// Login mocks base method.
func (m *MockAuthServiceInterface) Login(ctx context.Context, platformURL, email, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, platformURL, email, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// Login indicates an expected call of Login.
func (mr *MockAuthServiceInterfaceMockRecorder) Login(ctx, platformURL, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthServiceInterface)(nil).Login), ctx, platformURL, email, password)
}

// LoginInteractive mocks base method.
func (m *MockAuthServiceInterface) LoginInteractive(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginInteractive", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoginInteractive indicates an expected call of LoginInteractive.
func (mr *MockAuthServiceInterfaceMockRecorder) LoginInteractive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginInteractive", reflect.TypeOf((*MockAuthServiceInterface)(nil).LoginInteractive), ctx)
}

// Logout mocks base method.
func (m *MockAuthServiceInterface) Logout() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout")
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthServiceInterfaceMockRecorder) Logout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthServiceInterface)(nil).Logout))
}

// RequireAuth mocks base method.
func (m *MockAuthServiceInterface) RequireAuth() (*cli.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequireAuth")
	ret0, _ := ret[0].(*cli.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequireAuth indicates an expected call of RequireAuth.
func (mr *MockAuthServiceInterfaceMockRecorder) RequireAuth() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequireAuth", reflect.TypeOf((*MockAuthServiceInterface)(nil).RequireAuth))
}

// MockSyncServiceInterface is a mock of SyncServiceInterface interface.
type MockSyncServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSyncServiceInterfaceMockRecorder
}

// MockSyncServiceInterfaceMockRecorder is the mock recorder for MockSyncServiceInterface.
type MockSyncServiceInterfaceMockRecorder struct {
	mock *MockSyncServiceInterface
}

// NewMockSyncServiceInterface creates a new mock instance.
func NewMockSyncServiceInterface(ctrl *gomock.Controller) *MockSyncServiceInterface {
	mock := &MockSyncServiceInterface{ctrl: ctrl}
	mock.recorder = &MockSyncServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncServiceInterface) EXPECT() *MockSyncServiceInterfaceMockRecorder {
	return m.recorder
}

// GetAgentConfig mocks base method.
func (m *MockSyncServiceInterface) GetAgentConfig(idOrName string) (*cli.AgentConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentConfig", idOrName)
	ret0, _ := ret[0].(*cli.AgentConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentConfig indicates an expected call of GetAgentConfig.
func (mr *MockSyncServiceInterfaceMockRecorder) GetAgentConfig(idOrName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentConfig", reflect.TypeOf((*MockSyncServiceInterface)(nil).GetAgentConfig), idOrName)
}

// GetContainerStatus mocks base method.
func (m *MockSyncServiceInterface) GetContainerStatus(ctx context.Context) ([]cli.ContainerInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContainerStatus", ctx)
	ret0, _ := ret[0].([]cli.ContainerInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContainerStatus indicates an expected call of GetContainerStatus.
func (mr *MockSyncServiceInterfaceMockRecorder) GetContainerStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContainerStatus", reflect.TypeOf((*MockSyncServiceInterface)(nil).GetContainerStatus), ctx)
}

// GetLocalAgentConfigs mocks base method.
func (m *MockSyncServiceInterface) GetLocalAgentConfigs() ([]cli.AgentConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocalAgentConfigs")
	ret0, _ := ret[0].([]cli.AgentConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocalAgentConfigs indicates an expected call of GetLocalAgentConfigs.
func (mr *MockSyncServiceInterfaceMockRecorder) GetLocalAgentConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocalAgentConfigs", reflect.TypeOf((*MockSyncServiceInterface)(nil).GetLocalAgentConfigs))
}

// SetContainerManager mocks base method.
func (m *MockSyncServiceInterface) SetContainerManager(cm cli.ContainerManagerInterface) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetContainerManager", cm)
}

// SetContainerManager indicates an expected call of SetContainerManager.
func (mr *MockSyncServiceInterfaceMockRecorder) SetContainerManager(cm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetContainerManager", reflect.TypeOf((*MockSyncServiceInterface)(nil).SetContainerManager), cm)
}

// SetDockerClient mocks base method.
func (m *MockSyncServiceInterface) SetDockerClient(dockerClient *cli.DockerClient) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDockerClient", dockerClient)
}

// SetDockerClient indicates an expected call of SetDockerClient.
func (mr *MockSyncServiceInterfaceMockRecorder) SetDockerClient(dockerClient any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDockerClient", reflect.TypeOf((*MockSyncServiceInterface)(nil).SetDockerClient), dockerClient)
}

// StartContainers mocks base method.
func (m *MockSyncServiceInterface) StartContainers(ctx context.Context, workspacePath, apiKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartContainers", ctx, workspacePath, apiKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartContainers indicates an expected call of StartContainers.
func (mr *MockSyncServiceInterfaceMockRecorder) StartContainers(ctx, workspacePath, apiKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartContainers", reflect.TypeOf((*MockSyncServiceInterface)(nil).StartContainers), ctx, workspacePath, apiKey)
}

// StopContainers mocks base method.
func (m *MockSyncServiceInterface) StopContainers(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopContainers", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopContainers indicates an expected call of StopContainers.
func (mr *MockSyncServiceInterfaceMockRecorder) StopContainers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopContainers", reflect.TypeOf((*MockSyncServiceInterface)(nil).StopContainers), ctx)
}

// Sync mocks base method.
func (m *MockSyncServiceInterface) Sync(ctx context.Context) (*cli.SyncResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", ctx)
	ret0, _ := ret[0].(*cli.SyncResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sync indicates an expected call of Sync.
func (mr *MockSyncServiceInterfaceMockRecorder) Sync(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockSyncServiceInterface)(nil).Sync), ctx)
}

// SyncClaudeCode mocks base method.
func (m *MockSyncServiceInterface) SyncClaudeCode(ctx context.Context, targetDir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncClaudeCode", ctx, targetDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncClaudeCode indicates an expected call of SyncClaudeCode.
func (mr *MockSyncServiceInterfaceMockRecorder) SyncClaudeCode(ctx, targetDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncClaudeCode", reflect.TypeOf((*MockSyncServiceInterface)(nil).SyncClaudeCode), ctx, targetDir)
}

// MockAgentServiceInterface is a mock of AgentServiceInterface interface.
type MockAgentServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAgentServiceInterfaceMockRecorder
}

// MockAgentServiceInterfaceMockRecorder is the mock recorder for MockAgentServiceInterface.
type MockAgentServiceInterfaceMockRecorder struct {
	mock *MockAgentServiceInterface
}

// NewMockAgentServiceInterface creates a new mock instance.
func NewMockAgentServiceInterface(ctrl *gomock.Controller) *MockAgentServiceInterface {
	mock := &MockAgentServiceInterface{ctrl: ctrl}
	mock.recorder = &MockAgentServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentServiceInterface) EXPECT() *MockAgentServiceInterfaceMockRecorder {
	return m.recorder
}

// CheckForUpdates mocks base method.
func (m *MockAgentServiceInterface) CheckForUpdates(ctx context.Context, employeeID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckForUpdates", ctx, employeeID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckForUpdates indicates an expected call of CheckForUpdates.
func (mr *MockAgentServiceInterfaceMockRecorder) CheckForUpdates(ctx, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckForUpdates", reflect.TypeOf((*MockAgentServiceInterface)(nil).CheckForUpdates), ctx, employeeID)
}

// GetAgent mocks base method.
func (m *MockAgentServiceInterface) GetAgent(ctx context.Context, agentID string) (*cli.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgent", ctx, agentID)
	ret0, _ := ret[0].(*cli.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgent indicates an expected call of GetAgent.
func (mr *MockAgentServiceInterfaceMockRecorder) GetAgent(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgent", reflect.TypeOf((*MockAgentServiceInterface)(nil).GetAgent), ctx, agentID)
}

// GetLocalAgents mocks base method.
func (m *MockAgentServiceInterface) GetLocalAgents() ([]cli.AgentConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocalAgents")
	ret0, _ := ret[0].([]cli.AgentConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocalAgents indicates an expected call of GetLocalAgents.
func (mr *MockAgentServiceInterfaceMockRecorder) GetLocalAgents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocalAgents", reflect.TypeOf((*MockAgentServiceInterface)(nil).GetLocalAgents))
}

// ListAgents mocks base method.
func (m *MockAgentServiceInterface) ListAgents(ctx context.Context) ([]cli.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAgents", ctx)
	ret0, _ := ret[0].([]cli.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAgents indicates an expected call of ListAgents.
func (mr *MockAgentServiceInterfaceMockRecorder) ListAgents(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAgents", reflect.TypeOf((*MockAgentServiceInterface)(nil).ListAgents), ctx)
}

// ListEmployeeAgentConfigs mocks base method.
func (m *MockAgentServiceInterface) ListEmployeeAgentConfigs(ctx context.Context, employeeID string) ([]cli.EmployeeAgentConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmployeeAgentConfigs", ctx, employeeID)
	ret0, _ := ret[0].([]cli.EmployeeAgentConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEmployeeAgentConfigs indicates an expected call of ListEmployeeAgentConfigs.
func (mr *MockAgentServiceInterfaceMockRecorder) ListEmployeeAgentConfigs(ctx, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmployeeAgentConfigs", reflect.TypeOf((*MockAgentServiceInterface)(nil).ListEmployeeAgentConfigs), ctx, employeeID)
}

// RequestAgent mocks base method.
func (m *MockAgentServiceInterface) RequestAgent(ctx context.Context, employeeID, agentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestAgent", ctx, employeeID, agentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestAgent indicates an expected call of RequestAgent.
func (mr *MockAgentServiceInterfaceMockRecorder) RequestAgent(ctx, employeeID, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestAgent", reflect.TypeOf((*MockAgentServiceInterface)(nil).RequestAgent), ctx, employeeID, agentID)
}

// MockSkillsServiceInterface is a mock of SkillsServiceInterface interface.
type MockSkillsServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSkillsServiceInterfaceMockRecorder
}

// MockSkillsServiceInterfaceMockRecorder is the mock recorder for MockSkillsServiceInterface.
type MockSkillsServiceInterfaceMockRecorder struct {
	mock *MockSkillsServiceInterface
}

// NewMockSkillsServiceInterface creates a new mock instance.
func NewMockSkillsServiceInterface(ctrl *gomock.Controller) *MockSkillsServiceInterface {
	mock := &MockSkillsServiceInterface{ctrl: ctrl}
	mock.recorder = &MockSkillsServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSkillsServiceInterface) EXPECT() *MockSkillsServiceInterfaceMockRecorder {
	return m.recorder
}

// GetEmployeeSkill mocks base method.
func (m *MockSkillsServiceInterface) GetEmployeeSkill(ctx context.Context, skillID string) (*cli.EmployeeSkill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeSkill", ctx, skillID)
	ret0, _ := ret[0].(*cli.EmployeeSkill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeSkill indicates an expected call of GetEmployeeSkill.
func (mr *MockSkillsServiceInterfaceMockRecorder) GetEmployeeSkill(ctx, skillID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeSkill", reflect.TypeOf((*MockSkillsServiceInterface)(nil).GetEmployeeSkill), ctx, skillID)
}

// GetEmployeeSkillByName mocks base method.
func (m *MockSkillsServiceInterface) GetEmployeeSkillByName(ctx context.Context, name string) (*cli.EmployeeSkill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeSkillByName", ctx, name)
	ret0, _ := ret[0].(*cli.EmployeeSkill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeSkillByName indicates an expected call of GetEmployeeSkillByName.
func (mr *MockSkillsServiceInterfaceMockRecorder) GetEmployeeSkillByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeSkillByName", reflect.TypeOf((*MockSkillsServiceInterface)(nil).GetEmployeeSkillByName), ctx, name)
}

// GetLocalSkill mocks base method.
func (m *MockSkillsServiceInterface) GetLocalSkill(name string) (*cli.LocalSkillInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocalSkill", name)
	ret0, _ := ret[0].(*cli.LocalSkillInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocalSkill indicates an expected call of GetLocalSkill.
func (mr *MockSkillsServiceInterfaceMockRecorder) GetLocalSkill(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocalSkill", reflect.TypeOf((*MockSkillsServiceInterface)(nil).GetLocalSkill), name)
}

// GetLocalSkills mocks base method.
func (m *MockSkillsServiceInterface) GetLocalSkills() ([]cli.LocalSkillInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocalSkills")
	ret0, _ := ret[0].([]cli.LocalSkillInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocalSkills indicates an expected call of GetLocalSkills.
func (mr *MockSkillsServiceInterfaceMockRecorder) GetLocalSkills() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocalSkills", reflect.TypeOf((*MockSkillsServiceInterface)(nil).GetLocalSkills))
}

// GetSkill mocks base method.
func (m *MockSkillsServiceInterface) GetSkill(ctx context.Context, skillID string) (*cli.Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSkill", ctx, skillID)
	ret0, _ := ret[0].(*cli.Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSkill indicates an expected call of GetSkill.
func (mr *MockSkillsServiceInterfaceMockRecorder) GetSkill(ctx, skillID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSkill", reflect.TypeOf((*MockSkillsServiceInterface)(nil).GetSkill), ctx, skillID)
}

// GetSkillByName mocks base method.
func (m *MockSkillsServiceInterface) GetSkillByName(ctx context.Context, name string) (*cli.Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSkillByName", ctx, name)
	ret0, _ := ret[0].(*cli.Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSkillByName indicates an expected call of GetSkillByName.
func (mr *MockSkillsServiceInterfaceMockRecorder) GetSkillByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSkillByName", reflect.TypeOf((*MockSkillsServiceInterface)(nil).GetSkillByName), ctx, name)
}

// ListCatalogSkills mocks base method.
func (m *MockSkillsServiceInterface) ListCatalogSkills(ctx context.Context) ([]cli.Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCatalogSkills", ctx)
	ret0, _ := ret[0].([]cli.Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCatalogSkills indicates an expected call of ListCatalogSkills.
func (mr *MockSkillsServiceInterfaceMockRecorder) ListCatalogSkills(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCatalogSkills", reflect.TypeOf((*MockSkillsServiceInterface)(nil).ListCatalogSkills), ctx)
}

// ListEmployeeSkills mocks base method.
func (m *MockSkillsServiceInterface) ListEmployeeSkills(ctx context.Context) ([]cli.EmployeeSkill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmployeeSkills", ctx)
	ret0, _ := ret[0].([]cli.EmployeeSkill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEmployeeSkills indicates an expected call of ListEmployeeSkills.
func (mr *MockSkillsServiceInterfaceMockRecorder) ListEmployeeSkills(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmployeeSkills", reflect.TypeOf((*MockSkillsServiceInterface)(nil).ListEmployeeSkills), ctx)
}

// MockDockerClientInterface is a mock of DockerClientInterface interface.
type MockDockerClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDockerClientInterfaceMockRecorder
}

// MockDockerClientInterfaceMockRecorder is the mock recorder for MockDockerClientInterface.
type MockDockerClientInterfaceMockRecorder struct {
	mock *MockDockerClientInterface
}

// NewMockDockerClientInterface creates a new mock instance.
func NewMockDockerClientInterface(ctrl *gomock.Controller) *MockDockerClientInterface {
	mock := &MockDockerClientInterface{ctrl: ctrl}
	mock.recorder = &MockDockerClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDockerClientInterface) EXPECT() *MockDockerClientInterfaceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDockerClientInterface) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDockerClientInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDockerClientInterface)(nil).Close))
}

// CreateContainer mocks base method.
func (m *MockDockerClientInterface) CreateContainer(ctx context.Context, config *cli.DockerContainerConfig, hostConfig *cli.DockerHostConfig, networkConfig *cli.DockerNetworkConfig, containerName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContainer", ctx, config, hostConfig, networkConfig, containerName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateContainer indicates an expected call of CreateContainer.
func (mr *MockDockerClientInterfaceMockRecorder) CreateContainer(ctx, config, hostConfig, networkConfig, containerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContainer", reflect.TypeOf((*MockDockerClientInterface)(nil).CreateContainer), ctx, config, hostConfig, networkConfig, containerName)
}

// CreateNetwork mocks base method.
func (m *MockDockerClientInterface) CreateNetwork(ctx context.Context, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNetwork", ctx, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNetwork indicates an expected call of CreateNetwork.
func (mr *MockDockerClientInterfaceMockRecorder) CreateNetwork(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNetwork", reflect.TypeOf((*MockDockerClientInterface)(nil).CreateNetwork), ctx, name)
}

// GetContainerLogs mocks base method.
func (m *MockDockerClientInterface) GetContainerLogs(ctx context.Context, containerID string, follow bool) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContainerLogs", ctx, containerID, follow)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContainerLogs indicates an expected call of GetContainerLogs.
func (mr *MockDockerClientInterfaceMockRecorder) GetContainerLogs(ctx, containerID, follow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContainerLogs", reflect.TypeOf((*MockDockerClientInterface)(nil).GetContainerLogs), ctx, containerID, follow)
}

// GetVersion mocks base method.
func (m *MockDockerClientInterface) GetVersion(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersion indicates an expected call of GetVersion.
func (mr *MockDockerClientInterfaceMockRecorder) GetVersion(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockDockerClientInterface)(nil).GetVersion), ctx)
}

// ListContainers mocks base method.
func (m *MockDockerClientInterface) ListContainers(ctx context.Context, all bool, labelFilter map[string]string) ([]cli.ContainerInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListContainers", ctx, all, labelFilter)
	ret0, _ := ret[0].([]cli.ContainerInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListContainers indicates an expected call of ListContainers.
func (mr *MockDockerClientInterfaceMockRecorder) ListContainers(ctx, all, labelFilter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListContainers", reflect.TypeOf((*MockDockerClientInterface)(nil).ListContainers), ctx, all, labelFilter)
}

// NetworkExists mocks base method.
func (m *MockDockerClientInterface) NetworkExists(ctx context.Context, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NetworkExists", ctx, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NetworkExists indicates an expected call of NetworkExists.
func (mr *MockDockerClientInterfaceMockRecorder) NetworkExists(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetworkExists", reflect.TypeOf((*MockDockerClientInterface)(nil).NetworkExists), ctx, name)
}

// Ping mocks base method.
func (m *MockDockerClientInterface) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockDockerClientInterfaceMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockDockerClientInterface)(nil).Ping), ctx)
}

// PullImage mocks base method.
func (m *MockDockerClientInterface) PullImage(ctx context.Context, imageName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullImage", ctx, imageName)
	ret0, _ := ret[0].(error)
	return ret0
}

// PullImage indicates an expected call of PullImage.
func (mr *MockDockerClientInterfaceMockRecorder) PullImage(ctx, imageName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullImage", reflect.TypeOf((*MockDockerClientInterface)(nil).PullImage), ctx, imageName)
}

// RemoveContainer mocks base method.
func (m *MockDockerClientInterface) RemoveContainer(ctx context.Context, containerID string, force bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveContainer", ctx, containerID, force)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveContainer indicates an expected call of RemoveContainer.
func (mr *MockDockerClientInterfaceMockRecorder) RemoveContainer(ctx, containerID, force any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveContainer", reflect.TypeOf((*MockDockerClientInterface)(nil).RemoveContainer), ctx, containerID, force)
}

// RemoveContainerByName mocks base method.
func (m *MockDockerClientInterface) RemoveContainerByName(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveContainerByName", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveContainerByName indicates an expected call of RemoveContainerByName.
func (mr *MockDockerClientInterfaceMockRecorder) RemoveContainerByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveContainerByName", reflect.TypeOf((*MockDockerClientInterface)(nil).RemoveContainerByName), ctx, name)
}

// RemoveNetwork mocks base method.
func (m *MockDockerClientInterface) RemoveNetwork(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveNetwork", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveNetwork indicates an expected call of RemoveNetwork.
func (mr *MockDockerClientInterfaceMockRecorder) RemoveNetwork(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveNetwork", reflect.TypeOf((*MockDockerClientInterface)(nil).RemoveNetwork), ctx, name)
}

// StartContainer mocks base method.
func (m *MockDockerClientInterface) StartContainer(ctx context.Context, containerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartContainer", ctx, containerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartContainer indicates an expected call of StartContainer.
func (mr *MockDockerClientInterfaceMockRecorder) StartContainer(ctx, containerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartContainer", reflect.TypeOf((*MockDockerClientInterface)(nil).StartContainer), ctx, containerID)
}

// StopContainer mocks base method.
func (m *MockDockerClientInterface) StopContainer(ctx context.Context, containerID string, timeout *int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopContainer", ctx, containerID, timeout)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopContainer indicates an expected call of StopContainer.
func (mr *MockDockerClientInterfaceMockRecorder) StopContainer(ctx, containerID, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopContainer", reflect.TypeOf((*MockDockerClientInterface)(nil).StopContainer), ctx, containerID, timeout)
}

// StreamContainerLogs mocks base method.
func (m *MockDockerClientInterface) StreamContainerLogs(ctx context.Context, containerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamContainerLogs", ctx, containerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamContainerLogs indicates an expected call of StreamContainerLogs.
func (mr *MockDockerClientInterfaceMockRecorder) StreamContainerLogs(ctx, containerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamContainerLogs", reflect.TypeOf((*MockDockerClientInterface)(nil).StreamContainerLogs), ctx, containerID)
}

// MockContainerManagerInterface is a mock of ContainerManagerInterface interface.
type MockContainerManagerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockContainerManagerInterfaceMockRecorder
}

// MockContainerManagerInterfaceMockRecorder is the mock recorder for MockContainerManagerInterface.
type MockContainerManagerInterfaceMockRecorder struct {
	mock *MockContainerManagerInterface
}

// NewMockContainerManagerInterface creates a new mock instance.
func NewMockContainerManagerInterface(ctrl *gomock.Controller) *MockContainerManagerInterface {
	mock := &MockContainerManagerInterface{ctrl: ctrl}
	mock.recorder = &MockContainerManagerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContainerManagerInterface) EXPECT() *MockContainerManagerInterfaceMockRecorder {
	return m.recorder
}

// CleanupContainers mocks base method.
func (m *MockContainerManagerInterface) CleanupContainers(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupContainers", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupContainers indicates an expected call of CleanupContainers.
func (mr *MockContainerManagerInterfaceMockRecorder) CleanupContainers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupContainers", reflect.TypeOf((*MockContainerManagerInterface)(nil).CleanupContainers), ctx)
}

// GetContainerStatus mocks base method.
func (m *MockContainerManagerInterface) GetContainerStatus(ctx context.Context) ([]cli.ContainerInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContainerStatus", ctx)
	ret0, _ := ret[0].([]cli.ContainerInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContainerStatus indicates an expected call of GetContainerStatus.
func (mr *MockContainerManagerInterfaceMockRecorder) GetContainerStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContainerStatus", reflect.TypeOf((*MockContainerManagerInterface)(nil).GetContainerStatus), ctx)
}

// SetupNetwork mocks base method.
func (m *MockContainerManagerInterface) SetupNetwork(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupNetwork", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetupNetwork indicates an expected call of SetupNetwork.
func (mr *MockContainerManagerInterfaceMockRecorder) SetupNetwork(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupNetwork", reflect.TypeOf((*MockContainerManagerInterface)(nil).SetupNetwork), ctx)
}

// StartAgent mocks base method.
func (m *MockContainerManagerInterface) StartAgent(ctx context.Context, spec cli.AgentSpec, workspacePath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartAgent", ctx, spec, workspacePath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartAgent indicates an expected call of StartAgent.
func (mr *MockContainerManagerInterfaceMockRecorder) StartAgent(ctx, spec, workspacePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartAgent", reflect.TypeOf((*MockContainerManagerInterface)(nil).StartAgent), ctx, spec, workspacePath)
}

// StartMCPServer mocks base method.
func (m *MockContainerManagerInterface) StartMCPServer(ctx context.Context, spec cli.MCPServerSpec, workspacePath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartMCPServer", ctx, spec, workspacePath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartMCPServer indicates an expected call of StartMCPServer.
func (mr *MockContainerManagerInterfaceMockRecorder) StartMCPServer(ctx, spec, workspacePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartMCPServer", reflect.TypeOf((*MockContainerManagerInterface)(nil).StartMCPServer), ctx, spec, workspacePath)
}

// StopContainers mocks base method.
func (m *MockContainerManagerInterface) StopContainers(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopContainers", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopContainers indicates an expected call of StopContainers.
func (mr *MockContainerManagerInterfaceMockRecorder) StopContainers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopContainers", reflect.TypeOf((*MockContainerManagerInterface)(nil).StopContainers), ctx)
}
