// Code generated by MockGen. DO NOT EDIT.
// Source: ../sync/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=../sync/interfaces.go -destination=interfaces_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	api "github.com/sergeirastrigin/ubik-enterprise/services/cli/internal/api"
	config "github.com/sergeirastrigin/ubik-enterprise/services/cli/internal/config"
	sync "github.com/sergeirastrigin/ubik-enterprise/services/cli/internal/sync"
	gomock "go.uber.org/mock/gomock"
)

// MockConfigManagerInterface is a mock of ConfigManagerInterface interface.
type MockConfigManagerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockConfigManagerInterfaceMockRecorder
}

// MockConfigManagerInterfaceMockRecorder is the mock recorder for MockConfigManagerInterface.
type MockConfigManagerInterfaceMockRecorder struct {
	mock *MockConfigManagerInterface
}

// NewMockConfigManagerInterface creates a new mock instance.
func NewMockConfigManagerInterface(ctrl *gomock.Controller) *MockConfigManagerInterface {
	mock := &MockConfigManagerInterface{ctrl: ctrl}
	mock.recorder = &MockConfigManagerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigManagerInterface) EXPECT() *MockConfigManagerInterfaceMockRecorder {
	return m.recorder
}

// Clear mocks base method.
func (m *MockConfigManagerInterface) Clear() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear")
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear.
func (mr *MockConfigManagerInterfaceMockRecorder) Clear() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockConfigManagerInterface)(nil).Clear))
}

// GetConfigPath mocks base method.
func (m *MockConfigManagerInterface) GetConfigPath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigPath")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetConfigPath indicates an expected call of GetConfigPath.
func (mr *MockConfigManagerInterfaceMockRecorder) GetConfigPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigPath", reflect.TypeOf((*MockConfigManagerInterface)(nil).GetConfigPath))
}

// IsAuthenticated mocks base method.
func (m *MockConfigManagerInterface) IsAuthenticated() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAuthenticated")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAuthenticated indicates an expected call of IsAuthenticated.
func (mr *MockConfigManagerInterfaceMockRecorder) IsAuthenticated() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAuthenticated", reflect.TypeOf((*MockConfigManagerInterface)(nil).IsAuthenticated))
}

// IsTokenValid mocks base method.
func (m *MockConfigManagerInterface) IsTokenValid() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTokenValid")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTokenValid indicates an expected call of IsTokenValid.
func (mr *MockConfigManagerInterfaceMockRecorder) IsTokenValid() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTokenValid", reflect.TypeOf((*MockConfigManagerInterface)(nil).IsTokenValid))
}

// Load mocks base method.
func (m *MockConfigManagerInterface) Load() (*config.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load")
	ret0, _ := ret[0].(*config.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockConfigManagerInterfaceMockRecorder) Load() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockConfigManagerInterface)(nil).Load))
}

// Save mocks base method.
func (m *MockConfigManagerInterface) Save(cfg *config.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockConfigManagerInterfaceMockRecorder) Save(cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockConfigManagerInterface)(nil).Save), cfg)
}

// MockAPIClientInterface is a mock of APIClientInterface interface.
type MockAPIClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAPIClientInterfaceMockRecorder
}

// MockAPIClientInterfaceMockRecorder is the mock recorder for MockAPIClientInterface.
type MockAPIClientInterfaceMockRecorder struct {
	mock *MockAPIClientInterface
}

// NewMockAPIClientInterface creates a new mock instance.
func NewMockAPIClientInterface(ctrl *gomock.Controller) *MockAPIClientInterface {
	mock := &MockAPIClientInterface{ctrl: ctrl}
	mock.recorder = &MockAPIClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIClientInterface) EXPECT() *MockAPIClientInterfaceMockRecorder {
	return m.recorder
}

// GetClaudeCodeConfig mocks base method.
func (m *MockAPIClientInterface) GetClaudeCodeConfig(ctx context.Context) (*api.ClaudeCodeSyncResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClaudeCodeConfig", ctx)
	ret0, _ := ret[0].(*api.ClaudeCodeSyncResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClaudeCodeConfig indicates an expected call of GetClaudeCodeConfig.
func (mr *MockAPIClientInterfaceMockRecorder) GetClaudeCodeConfig(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClaudeCodeConfig", reflect.TypeOf((*MockAPIClientInterface)(nil).GetClaudeCodeConfig), ctx)
}

// GetEffectiveClaudeToken mocks base method.
func (m *MockAPIClientInterface) GetEffectiveClaudeToken(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEffectiveClaudeToken", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEffectiveClaudeToken indicates an expected call of GetEffectiveClaudeToken.
func (mr *MockAPIClientInterfaceMockRecorder) GetEffectiveClaudeToken(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEffectiveClaudeToken", reflect.TypeOf((*MockAPIClientInterface)(nil).GetEffectiveClaudeToken), ctx)
}

// GetMyResolvedAgentConfigs mocks base method.
func (m *MockAPIClientInterface) GetMyResolvedAgentConfigs(ctx context.Context) ([]api.AgentConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyResolvedAgentConfigs", ctx)
	ret0, _ := ret[0].([]api.AgentConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyResolvedAgentConfigs indicates an expected call of GetMyResolvedAgentConfigs.
func (mr *MockAPIClientInterfaceMockRecorder) GetMyResolvedAgentConfigs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyResolvedAgentConfigs", reflect.TypeOf((*MockAPIClientInterface)(nil).GetMyResolvedAgentConfigs), ctx)
}

// MockAuthServiceInterface is a mock of AuthServiceInterface interface.
type MockAuthServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceInterfaceMockRecorder
}

// MockAuthServiceInterfaceMockRecorder is the mock recorder for MockAuthServiceInterface.
type MockAuthServiceInterfaceMockRecorder struct {
	mock *MockAuthServiceInterface
}

// NewMockAuthServiceInterface creates a new mock instance.
func NewMockAuthServiceInterface(ctrl *gomock.Controller) *MockAuthServiceInterface {
	mock := &MockAuthServiceInterface{ctrl: ctrl}
	mock.recorder = &MockAuthServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthServiceInterface) EXPECT() *MockAuthServiceInterfaceMockRecorder {
	return m.recorder
}

// RequireAuth mocks base method.
func (m *MockAuthServiceInterface) RequireAuth() (*config.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequireAuth")
	ret0, _ := ret[0].(*config.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequireAuth indicates an expected call of RequireAuth.
func (mr *MockAuthServiceInterfaceMockRecorder) RequireAuth() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequireAuth", reflect.TypeOf((*MockAuthServiceInterface)(nil).RequireAuth))
}

// MockDockerClientInterface is a mock of DockerClientInterface interface.
type MockDockerClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDockerClientInterfaceMockRecorder
}

// MockDockerClientInterfaceMockRecorder is the mock recorder for MockDockerClientInterface.
type MockDockerClientInterfaceMockRecorder struct {
	mock *MockDockerClientInterface
}

// NewMockDockerClientInterface creates a new mock instance.
func NewMockDockerClientInterface(ctrl *gomock.Controller) *MockDockerClientInterface {
	mock := &MockDockerClientInterface{ctrl: ctrl}
	mock.recorder = &MockDockerClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDockerClientInterface) EXPECT() *MockDockerClientInterfaceMockRecorder {
	return m.recorder
}

// GetVersion mocks base method.
func (m *MockDockerClientInterface) GetVersion(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersion indicates an expected call of GetVersion.
func (mr *MockDockerClientInterfaceMockRecorder) GetVersion(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockDockerClientInterface)(nil).GetVersion), ctx)
}

// Ping mocks base method.
func (m *MockDockerClientInterface) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockDockerClientInterfaceMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockDockerClientInterface)(nil).Ping), ctx)
}

// MockContainerManagerInterface is a mock of ContainerManagerInterface interface.
type MockContainerManagerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockContainerManagerInterfaceMockRecorder
}

// MockContainerManagerInterfaceMockRecorder is the mock recorder for MockContainerManagerInterface.
type MockContainerManagerInterfaceMockRecorder struct {
	mock *MockContainerManagerInterface
}

// NewMockContainerManagerInterface creates a new mock instance.
func NewMockContainerManagerInterface(ctrl *gomock.Controller) *MockContainerManagerInterface {
	mock := &MockContainerManagerInterface{ctrl: ctrl}
	mock.recorder = &MockContainerManagerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContainerManagerInterface) EXPECT() *MockContainerManagerInterfaceMockRecorder {
	return m.recorder
}

// GetContainerStatus mocks base method.
func (m *MockContainerManagerInterface) GetContainerStatus(ctx context.Context) ([]sync.ContainerInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContainerStatus", ctx)
	ret0, _ := ret[0].([]sync.ContainerInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContainerStatus indicates an expected call of GetContainerStatus.
func (mr *MockContainerManagerInterfaceMockRecorder) GetContainerStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContainerStatus", reflect.TypeOf((*MockContainerManagerInterface)(nil).GetContainerStatus), ctx)
}

// SetupNetwork mocks base method.
func (m *MockContainerManagerInterface) SetupNetwork(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupNetwork", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetupNetwork indicates an expected call of SetupNetwork.
func (mr *MockContainerManagerInterfaceMockRecorder) SetupNetwork(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupNetwork", reflect.TypeOf((*MockContainerManagerInterface)(nil).SetupNetwork), ctx)
}

// StartAgent mocks base method.
func (m *MockContainerManagerInterface) StartAgent(ctx context.Context, spec sync.AgentSpec, workspacePath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartAgent", ctx, spec, workspacePath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartAgent indicates an expected call of StartAgent.
func (mr *MockContainerManagerInterfaceMockRecorder) StartAgent(ctx, spec, workspacePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartAgent", reflect.TypeOf((*MockContainerManagerInterface)(nil).StartAgent), ctx, spec, workspacePath)
}

// StartMCPServer mocks base method.
func (m *MockContainerManagerInterface) StartMCPServer(ctx context.Context, spec sync.MCPServerSpec, workspacePath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartMCPServer", ctx, spec, workspacePath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartMCPServer indicates an expected call of StartMCPServer.
func (mr *MockContainerManagerInterfaceMockRecorder) StartMCPServer(ctx, spec, workspacePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartMCPServer", reflect.TypeOf((*MockContainerManagerInterface)(nil).StartMCPServer), ctx, spec, workspacePath)
}

// StopContainers mocks base method.
func (m *MockContainerManagerInterface) StopContainers(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopContainers", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopContainers indicates an expected call of StopContainers.
func (mr *MockContainerManagerInterfaceMockRecorder) StopContainers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopContainers", reflect.TypeOf((*MockContainerManagerInterface)(nil).StopContainers), ctx)
}

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// GetAgentConfig mocks base method.
func (m *MockServiceInterface) GetAgentConfig(idOrName string) (*api.AgentConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentConfig", idOrName)
	ret0, _ := ret[0].(*api.AgentConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentConfig indicates an expected call of GetAgentConfig.
func (mr *MockServiceInterfaceMockRecorder) GetAgentConfig(idOrName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentConfig", reflect.TypeOf((*MockServiceInterface)(nil).GetAgentConfig), idOrName)
}

// GetContainerStatus mocks base method.
func (m *MockServiceInterface) GetContainerStatus(ctx context.Context) ([]sync.ContainerInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContainerStatus", ctx)
	ret0, _ := ret[0].([]sync.ContainerInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContainerStatus indicates an expected call of GetContainerStatus.
func (mr *MockServiceInterfaceMockRecorder) GetContainerStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContainerStatus", reflect.TypeOf((*MockServiceInterface)(nil).GetContainerStatus), ctx)
}

// GetLocalAgentConfigs mocks base method.
func (m *MockServiceInterface) GetLocalAgentConfigs() ([]api.AgentConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocalAgentConfigs")
	ret0, _ := ret[0].([]api.AgentConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocalAgentConfigs indicates an expected call of GetLocalAgentConfigs.
func (mr *MockServiceInterfaceMockRecorder) GetLocalAgentConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocalAgentConfigs", reflect.TypeOf((*MockServiceInterface)(nil).GetLocalAgentConfigs))
}

// SetContainerManager mocks base method.
func (m *MockServiceInterface) SetContainerManager(cm sync.ContainerManagerInterface) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetContainerManager", cm)
}

// SetContainerManager indicates an expected call of SetContainerManager.
func (mr *MockServiceInterfaceMockRecorder) SetContainerManager(cm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetContainerManager", reflect.TypeOf((*MockServiceInterface)(nil).SetContainerManager), cm)
}

// SetDockerClient mocks base method.
func (m *MockServiceInterface) SetDockerClient(dockerClient sync.DockerClientInterface) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDockerClient", dockerClient)
}

// SetDockerClient indicates an expected call of SetDockerClient.
func (mr *MockServiceInterfaceMockRecorder) SetDockerClient(dockerClient any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDockerClient", reflect.TypeOf((*MockServiceInterface)(nil).SetDockerClient), dockerClient)
}

// StartContainers mocks base method.
func (m *MockServiceInterface) StartContainers(ctx context.Context, workspacePath, apiKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartContainers", ctx, workspacePath, apiKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartContainers indicates an expected call of StartContainers.
func (mr *MockServiceInterfaceMockRecorder) StartContainers(ctx, workspacePath, apiKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartContainers", reflect.TypeOf((*MockServiceInterface)(nil).StartContainers), ctx, workspacePath, apiKey)
}

// StopContainers mocks base method.
func (m *MockServiceInterface) StopContainers(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopContainers", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopContainers indicates an expected call of StopContainers.
func (mr *MockServiceInterfaceMockRecorder) StopContainers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopContainers", reflect.TypeOf((*MockServiceInterface)(nil).StopContainers), ctx)
}

// Sync mocks base method.
func (m *MockServiceInterface) Sync(ctx context.Context) (*sync.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", ctx)
	ret0, _ := ret[0].(*sync.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sync indicates an expected call of Sync.
func (mr *MockServiceInterfaceMockRecorder) Sync(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockServiceInterface)(nil).Sync), ctx)
}

// SyncClaudeCode mocks base method.
func (m *MockServiceInterface) SyncClaudeCode(ctx context.Context, targetDir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncClaudeCode", ctx, targetDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncClaudeCode indicates an expected call of SyncClaudeCode.
func (mr *MockServiceInterfaceMockRecorder) SyncClaudeCode(ctx, targetDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncClaudeCode", reflect.TypeOf((*MockServiceInterface)(nil).SyncClaudeCode), ctx, targetDir)
}
