name: 'Setup Go Code Generation Tools'
description: 'Install and cache Go code generation tools (sqlc, oapi-codegen, mockgen)'
runs:
  using: 'composite'
  steps:
    - name: Cache Go tools
      uses: actions/cache@v4
      id: go-tools-cache
      with:
        path: ~/go/bin
        key: ${{ runner.os }}-go-tools-${{ hashFiles('**/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-go-tools-

    - name: Install code generation tools
      if: steps.go-tools-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
        go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest
        go install go.uber.org/mock/mockgen@latest

    - name: Add Go bin to PATH
      shell: bash
      run: echo "$HOME/go/bin" >> $GITHUB_PATH
