#!/usr/bin/env python3
"""
Generate full ERD overview (docs/ERD.md) from tbls schema.json output.
This ensures ERD.md is always in sync with the actual database schema.

Usage:
    python3 scripts/generate-erd-overview.py

Input:  docs/schema.json (generated by tbls)
Output: docs/ERD.md (Mermaid ERD diagram)
"""

import json
import sys
from pathlib import Path


def load_schema(schema_path: Path) -> dict:
    """Load schema.json generated by tbls."""
    with open(schema_path, 'r') as f:
        return json.load(f)


def get_table_short_name(full_name: str) -> str:
    """Convert 'public.employees' to 'employees'."""
    return full_name.split('.')[-1]


def get_type_display(column_type: str) -> str:
    """Convert PostgreSQL types to Mermaid-friendly display."""
    # Remove length specifications for display
    type_map = {
        'uuid': 'uuid',
        'character varying': 'varchar',
        'timestamp without time zone': 'timestamp',
        'timestamp with time zone': 'timestamptz',
        'integer': 'int',
        'bigint': 'bigint',
        'numeric': 'decimal',
        'boolean': 'boolean',
        'text': 'text',
        'jsonb': 'jsonb',
    }

    # Try to match known types
    for pg_type, display_type in type_map.items():
        if pg_type in column_type.lower():
            return display_type

    # Default: use as-is but clean up
    return column_type.replace('(', '').replace(')', '').replace(' ', '_')


def generate_relationships(schema: dict) -> list:
    """Extract all foreign key relationships."""
    relationships = []

    for table in schema['tables']:
        if table['type'] != 'BASE TABLE':
            continue

        table_name = get_table_short_name(table['name'])

        # Find foreign key constraints
        for constraint in table.get('constraints', []):
            if constraint['type'] != 'FOREIGN KEY':
                continue

            # Extract referenced table from constraint definition
            # Example: "FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE"
            definition = constraint['def']

            if 'REFERENCES' in definition:
                parts = definition.split('REFERENCES')[1].strip()
                referenced_table = parts.split('(')[0].strip()
                referenced_table = get_table_short_name(referenced_table)

                # Check if it's nullable (optional relationship)
                constraint_name = constraint['name']
                column_name = constraint_name.replace(f'{table_name}_', '').replace('_fkey', '')

                # Find if column is nullable
                is_nullable = False
                for col in table.get('columns', []):
                    if column_name in col['name']:
                        is_nullable = col.get('nullable', False)
                        break

                # Determine relationship cardinality
                # ||--o{ means one-to-many (required parent)
                # ||--|| means one-to-one (required parent)
                # }o--|| means many-to-one
                if is_nullable:
                    relationships.append(f'    {referenced_table} ||--o{{ {table_name} : "has"')
                else:
                    relationships.append(f'    {referenced_table} ||--o{{ {table_name} : "has"')

    return relationships


def generate_table_definitions(schema: dict) -> dict:
    """Generate Mermaid table definitions grouped by category."""

    tables = {
        'organizations': [],
        'subscriptions': [],
        'teams': [],
        'roles': [],
        'employees': [],
        'sessions': [],
        'agent_catalog': [],
        'tools': [],
        'policies': [],
        'agent_tools': [],
        'agent_policies': [],
        'team_policies': [],
        'employee_agent_configs': [],
        'mcp_categories': [],
        'mcp_catalog': [],
        'employee_mcp_configs': [],
        'agent_requests': [],
        'approvals': [],
        'activity_logs': [],
        'usage_records': [],
    }

    for table in schema['tables']:
        if table['type'] != 'BASE TABLE':
            continue

        table_name = get_table_short_name(table['name'])
        if table_name not in tables:
            continue

        # Build table definition
        lines = [f'    {table_name} {{']

        for col in table['columns']:
            col_name = col['name']
            col_type = get_type_display(col['type'])

            # Determine if PK, FK, or UK
            suffix = ''

            # Check if primary key
            for constraint in table.get('constraints', []):
                if constraint['type'] == 'PRIMARY KEY' and col_name in constraint['def']:
                    suffix = ' PK'
                    break

            # Check if foreign key
            if not suffix:
                for constraint in table.get('constraints', []):
                    if constraint['type'] == 'FOREIGN KEY' and col_name in constraint['def']:
                        suffix = ' FK'
                        break

            # Check if unique key
            if not suffix:
                for constraint in table.get('constraints', []):
                    if constraint['type'] == 'UNIQUE' and col_name in constraint['def'] and col_name != 'id':
                        suffix = ' UK'
                        break

            lines.append(f'        {col_type} {col_name}{suffix}')

        lines.append('    }')
        tables[table_name] = lines

    return tables


def generate_erd_md(schema: dict) -> str:
    """Generate complete ERD.md content."""

    relationships = generate_relationships(schema)
    tables = generate_table_definitions(schema)

    # Count tables and views
    base_tables = [t for t in schema['tables'] if t['type'] == 'BASE TABLE']
    views = [t for t in schema['tables'] if t['type'] == 'VIEW']

    output = f"""# Enterprise AI Agent Management Platform - Entity Relationship Diagram

## Database Schema Overview

This Mermaid ERD diagram visualizes all tables and their relationships in the Ubik Enterprise platform.

**⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY**
- Generated from: `docs/schema.json`
- Script: `scripts/generate-erd-overview.py`
- To update: `make generate-erd`

```mermaid
erDiagram
    %% Core Organization Structure
"""

    # Add relationships
    for rel in relationships:
        output += rel + '\n'

    output += '\n    %% Table Definitions\n'

    # Add table definitions in order
    for table_name in tables:
        if tables[table_name]:
            output += '\n'.join(tables[table_name]) + '\n    \n'

    output += '```\n\n'

    # Add table groups section
    output += """## Table Groups

### 🏢 Core Organization (5 tables)
- **organizations** - Top-level tenant
- **subscriptions** - Billing and budget tracking
- **teams** - Group employees
- **roles** - Define permissions
- **employees** - User accounts

### 🤖 Agent Management (7 tables)
- **agent_catalog** - Available AI agents (Claude Code, Cursor, etc.)
- **tools** - Available tools (fs, git, http, etc.)
- **policies** - Usage policies and restrictions
- **agent_tools** - Many-to-many: agents ↔ tools
- **agent_policies** - Many-to-many: agents ↔ policies
- **team_policies** - Team-specific policy overrides
- **employee_agent_configs** - Per-employee agent instances

### 🔌 MCP Configuration (3 tables)
- **mcp_categories** - Organize MCP servers
- **mcp_catalog** - Available MCP servers
- **employee_mcp_configs** - Per-employee MCP instances

### 🔐 Authentication (1 table)
- **sessions** - JWT session tracking

### ✅ Approvals (2 tables)
- **agent_requests** - Employee requests for agents/MCPs
- **approvals** - Manager approval workflow

### 📊 Analytics (2 tables)
- **activity_logs** - Audit trail
- **usage_records** - Cost and resource tracking

## Key Relationships

### Multi-Tenancy
```
organizations (1) ──→ (N) employees
organizations (1) ──→ (N) teams
organizations (1) ──→ (N) activity_logs
```

### Employee Configuration
```
employees (1) ──→ (N) employee_agent_configs
employees (1) ──→ (N) employee_mcp_configs
employees (1) ──→ (N) sessions
```

### Agent System
```
agent_catalog (1) ──→ (N) employee_agent_configs
agent_catalog (M) ←→ (N) tools (via agent_tools)
agent_catalog (M) ←→ (N) policies (via agent_policies)
```

### MCP System
```
mcp_catalog (1) ──→ (N) employee_mcp_configs
mcp_categories (1) ──→ (N) mcp_catalog
```

### Approval Workflow
```
agent_requests (1) ──→ (N) approvals
employees (1) ──→ (N) agent_requests (requester)
employees (1) ──→ (N) approvals (approver)
```

## Views

The schema also includes {len(views)} materialized views for common queries:

"""

    for view in views:
        view_name = get_table_short_name(view['name'])
        output += f'{len([v for v in views if get_table_short_name(v["name"]) <= view_name])}. **{view_name}** - '

        # Add descriptions
        descriptions = {
            'v_employee_agents': 'Employee agents with catalog details',
            'v_employee_mcps': 'Employee MCPs with catalog details',
            'v_pending_approvals': 'Pending approval requests with context',
        }
        output += descriptions.get(view_name, 'View details') + '\n'

    output += f"""
## Indexes

All tables have appropriate indexes on:
- Primary keys (id)
- Foreign keys
- Unique constraints (email, slug, sync_token)
- Frequently queried columns (status, org_id, created_at)

## Database Statistics

- **Total Tables**: {len(base_tables)}
- **Junction Tables**: 3 (agent_tools, agent_policies, team_policies)
- **Views**: {len(views)}
- **Total Columns**: ~{sum(len(t.get('columns', [])) for t in base_tables)}
- **Foreign Keys**: {sum(len([c for c in t.get('constraints', []) if c['type'] == 'FOREIGN KEY']) for t in base_tables)}+
- **Indexes**: {sum(len(t.get('indexes', [])) for t in base_tables)}+

## Legend

- **PK**: Primary Key
- **FK**: Foreign Key
- **UK**: Unique Key
- **(1) ──→ (N)**: One-to-Many relationship
- **(M) ←→ (N)**: Many-to-Many relationship

---

**Schema Version**: 1.0.0
**Database**: PostgreSQL 15+
"""

    return output


def main():
    """Main entry point."""
    # Paths
    project_root = Path(__file__).parent.parent
    schema_path = project_root / 'docs' / 'schema.json'
    output_path = project_root / 'docs' / 'ERD.md'

    # Validate input exists
    if not schema_path.exists():
        print(f'❌ Error: {schema_path} not found', file=sys.stderr)
        print('💡 Run "make generate-erd" to generate schema.json first', file=sys.stderr)
        sys.exit(1)

    # Load and process
    print(f'📖 Reading schema from {schema_path}')
    schema = load_schema(schema_path)

    print('🔧 Generating Mermaid ERD...')
    erd_content = generate_erd_md(schema)

    print(f'💾 Writing to {output_path}')
    with open(output_path, 'w') as f:
        f.write(erd_content)

    print(f'✅ ERD.md generated successfully!')
    print(f'   - Tables: {len([t for t in schema["tables"] if t["type"] == "BASE TABLE"])}')
    print(f'   - Views: {len([t for t in schema["tables"] if t["type"] == "VIEW"])}')
    print(f'   - Output: {output_path}')


if __name__ == '__main__':
    main()
